fix(bug): hostilize Korath mission spawns
endless-sky/Endless-Sky-Delta pull request #125
Opened 2024-11-04 15:47 UTC by TheGiraffe3

**Bug Fix**

## Summary
Some of the mission-spawned Korath ships didn't get changed to Kor Alaji.

2024-11-04 20:00 UTC, Zitchas commented
@UnorderedSigh @ravenshining 

Could one or both of you take a look at these to double check the right fleets are being used, since it deals with Korath fleets? Thank you!

2024-11-05 21:59 UTC, ravenshining commented
It wouldn't be the Alaji in Parca, it would most likely be the Isaha.  I take it this is happening when you have both played the Korath intro and gotten them to not be hostile, *and* started the Remnant story?  At someplace or another there ought to be a lock out...

Or, for this case, when you take that mission, your rep with the Isaha takes a hit to put you back in the negatives.

2024-11-06 03:49 UTC, TheGiraffe3 commented
The pilot that I saw this on hadn't done any missions related to the Korath (hadn't yet discovered Misam) except for during the Remnant storyline.

2024-11-10 16:33 UTC, ravenshining requested changes
Now I've had a closer look, I've got some more things to revert / fix.

If the player is fully committed to the Remnant storyline, then normal Korath *should* be hostile.  Generally we try to avoid *needing* to kill factions besides the Alaji, but note that some of these missions are taking place in or near Korath space.  Defending yourself against raiders is one thing, but if you take the fight to them, the Korath will not be pleased.

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 side missions.txt
> +		government "Kor Alaji"
Sorry, when I said Parca I meant that whole cluster of systems

```suggestion
		government "Kor Isaha"
```

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 side missions.txt
> +		fleet "Kor Alaji Raid"
```suggestion
		fleet "Kor Isaha Raid"
```

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 cognizance.txt
> +		government "Kor Alaji"
These are scouts testing a new prototype and exploring new space, not fanatics attacking the remnant.

```suggestion
		government "Korath"
```

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 cognizance.txt
>  	npc kill
If they aren't fanatics, perhaps it is enough just to stop these poor stranded fighters from snooping about, @Zitchas ?

```suggestion
	npc disable
```

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 side missions.txt
> +		government "Kor Alaji"
This is a prototype ship in a Korath system, not someone attacking the Remnant.

```suggestion
		government "Korath"
```

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 side missions.txt
> +		government "Kor Alaji"
As the mission suggests, this is not a warship.

```suggestion
		government "Korath"
```

2024-11-10 16:33 UTC, ravenshining commented on data/remnant/remnant 2 side missions.txt
> +		government "Kor Alaji"
Not a warship.

```suggestion
		government "Korath"
```

2024-11-10 19:21 UTC, Zitchas commented on data/remnant/remnant 2 cognizance.txt
>  	npc kill
Sure, I can work with that.

2024-11-11 13:05 UTC, ravenshining approved these changes
Looks good.  We should at some point take a deeper look into how hostility is/isn't affected and at what points to cut off mission availability. @UnorderedSigh may know more (and also reminder for both of us to port these changes to the ESC PR)

2024-11-11 13:07 UTC, merged