feat(data): Two more person ships: Intola and Verdorve
endless-sky/Endless-Sky-Delta pull request #144
Opened 2024-11-16 14:18 UTC by TheGiraffe3

**Content (Person Ships)**

## Summary

Follow-up to #136 and #135. Re-PR of #143 after a git mistake.
Intola is a Scout with two Heavy Lasers as armament. I wondered about giving it a Quantum Keystone, but that's a little spoilery.
Verdorve's captain loves plasma weapons and engines, and the Splinter Verdorve flies uses nothing but plasma.

Also increases the person spawn rate by a somewhat extreme rate: twenty minutes on average to two and a half.

2024-11-16 21:00 UTC, Zitchas commented on data/gamerules.txt
> +	# DEFAULT: 9000 frames (two and a half minutes)
```suggestion
	# DEFAULT: 36000 frames (ten minutes)
```

I like the sentiment, but I think boosting the person spawn rate shorter than ten minutes is premature at this point. Probably another twenty people or so before we can start looking at making it shorter than ten.

2024-11-16 21:00 UTC, Zitchas commented on data/gamerules.txt
> +	"person spawn period" 9000
```suggestion
	"person spawn period" 36000
```

2024-11-16 21:13 UTC, Zitchas requested changes
Overall I like them. They have some fun dialog.

I do think it is s little pre mature to boost the spawn rate that far, though I definitely agree with bringing it back to ten from twenty...

2024-11-17 03:54 UTC, TheGiraffe3 commented
I kind of want to make a new "Anti-Pirate" government for these two.
They don't care a bit about any of the human factions, but want to shoot pirates on sight.

2024-11-17 11:21 UTC, Zitchas approved these changes
Back in one of the EV games there were two merchant governments. The default merchant ran in the face of danger, consistently. They avoid *any* combat to the best of their ability. Then there was the "Brave merchant" that acts like our current one, which would seek out enemies and the like and only run away once they got damaged a bunch. Kind of missing that behavior. It always seems weird to me that so many merchants will charge into combat.

For now, though, I think it looks good.

2024-11-17 11:35 UTC, TheGiraffe3 commented
Alright, sounds good.
I think if we use personalities correctly we could get that behavior, but yeah, not as part of a government... yet.

2024-11-17 13:17 UTC, merged