Code(feat) fighter ai
endless-sky/Endless-Sky-Delta pull request #17
Opened 2023-04-20 22:45 UTC by Zitchas

**Feature:** This PR implements the RearAttack pattern for high speed ships as detailed in Revamp

## Feature Details
This is an attack pattern aimed primarily at fighters, causing them to preferentially circle the target ship and focus on attacking the rear of it, thus keeping them out of the line of fire of any guns it might have.

It's not actually working yet, although it does build. I've been testing it with a job that spawns a vanguard with 3x the mass (thus slowing down its turning) and a pack of Terns to attack it (which have 3x the normal engines and their hull reduced to 0 mass, thus they move very fast)

2023-04-21 16:52 UTC, Zitchas commented
https://youtu.be/tB5eZiIUNOc 
This is a short clip of a flight of test fighters attacking a test vanguard. The vanguard has +1000 mass compared to normal, and the fighters are actually terns whose anvil engines provide about 5x more thrust than usual. They also have double the drag to keep their top speed from getting too big. They are using a modified finch sprite with large swaths of orange painted onto it to make the swizzle changes extremely obvious. The code for the Rear Attack routine has a bunch of swizzle changes programmed into it so that we can see what part of the code they are in as they move around. Note, none of the terns have cloaks, so when they turn cloaking red they're just denoting that they are in the "in front" part of the code.

cloaking red if in front
orange if atSide
salmon if notbehind
blue if behind but too far away
purplish if behind but too close
neon green if behind and in range
pink is all else

2023-04-25 13:02 UTC, Zitchas commented
Tried something new, and actually kind of got the desired behavior. Not entirely sure why it's working, but it is fairly consistent for the test job.

https://youtu.be/oxMLOLVIS8A

2023-04-26 19:20 UTC, RisingLeaf reviewed
Are you going to use these variables?

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	Point offset = target.Position() - target.Facing().Unit() * weaponsRange;
```suggestion
```

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	Point frontAvoid = (direction.Cross(ship.Facing().Unit()) < 0. ? northWest : northEast);
```suggestion
```

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	Point rearAvoid = (direction.Cross(target.Facing().Unit()) > 0. ? southWest : southEast);
```suggestion
```

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	bool justLeft = direction.Unit().Dot(target.Facing().Unit()) < -.8 && direction.Cross(target.Facing().Unit()) > 0;
```suggestion
```

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	bool justRight = direction.Unit().Dot(target.Facing().Unit()) < -.8 && direction.Cross(target.Facing().Unit()) <= 0;
```suggestion
```

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	bool atSide = (!inFront && !isBehind);
```suggestion
```

2023-04-26 19:20 UTC, RisingLeaf commented on source/AI.cpp
> +	double speed = ship.MaxVelocity();
```suggestion
```

2023-04-27 13:26 UTC, Zitchas commented
I don't know. Obviously they aren't being used right now, but they were used in VitalChip's original code to achieve more (and better) functionality than I am getting now. I've left them in for now because they might help me get to that better level. That being said, my brain's a bit fuzzy right now, so not sure when I'll be continuing work on this.

2024-09-12 04:19 UTC, TheGiraffe3 requested changes

2024-09-12 04:19 UTC, TheGiraffe3 commented on source/AI.cpp
> +	bool outerRadius = direction.Length() < targetTurretRange * 1.2; // should be max target gun & turget turret range
```suggestion
	bool outerRadius = direction.Length() < targetTurretRange * 1.2; // should be max target gun & turret range
```

2024-09-12 04:20 UTC, TheGiraffe3 commented
> I don't know. Obviously they aren't being used right now, but they were used in VitalChip's original code to achieve more (and better) functionality than I am getting now. I've left them in for now because they might help me get to that better level. That being said, my brain's a bit fuzzy right now, so not sure when I'll be continuing work on this.

Maybe just comment them out for now?

2024-10-05 18:44 UTC, Zitchas commented
> Are you going to use these variables?

Yes, I was intending to use them. Not sure about all of them or where exactly, but the AI is something that needs a lot of work and complexity.

2025-03-16 10:21 UTC, Zitchas commented
This is probably never going to be picked up again, so closing.

2025-03-16 10:21 UTC, closed without merging