Scanning for the Electronic Warfare System
endless-sky/Endless-Sky-Delta pull request #71
Opened 2024-07-18 12:57 UTC by TheGiraffe3

**Bug fix**

This PR addresses the bug/feature described in issue none

## Summary
@Zitchas this adds the different types of scan power to the Electronic Warfare System, which I think you forgot in #70.

## Screenshots
None.

## Usage examples
N/A

## Testing Done
None.

## Save File
This save file can be used to test these changes:
None.

## Artwork Checklist
N/A

## Wiki Update
N/A

## Performance Impact
N/A

2024-07-18 13:05 UTC, Zitchas commented on data/sheragi/sheragi outfits.txt
> +	"strategic scan power" 20
```suggestion
```

Just a note here: "Strategic Scan" is, like "Tactical Scan" actually a conglomerate of the various movement related information types. So having it here alongside them doubles up on things.

2024-07-18 13:05 UTC, Zitchas commented
Thank you, yes, I did forget about that one. Good catch!

2024-07-18 13:27 UTC, TheGiraffe3 commented on data/sheragi/sheragi outfits.txt
> +	"strategic scan power" 20
Wasn't aware, thanks.

2024-07-18 14:06 UTC, Zitchas commented
@Karirawri 

If you are around and can provide some input; what would the strengths and weaknesses of the Sheragi sensor system be?

2024-07-18 15:29 UTC, Zitchas commented
I'm not sure if Karirawri or Warlord Mike (DM'd on Discord) are around to provide insight into the Sheragi strengths and weaknesses. I'll take a stab at some stats sometime in the next day or two and we can move forward on this. If they arrive after we've moved forward we can make subsequent PR's to take their input into account.

2024-07-20 04:14 UTC, Zitchas requested changes
I consulted with Warlord Mike (of the Sheragi Saga, so one of the experts on the Sheragi in my books), and he suggested crew and weapon ranges being the best fit. 

I'd say leave rangefinding and thermal in as well. I've suggested the relevant changes.

2024-07-20 04:14 UTC, Zitchas commented on data/sheragi/sheragi outfits.txt
> +	"fuel scan power" 30
```suggestion
```

2024-07-20 04:14 UTC, Zitchas commented on data/sheragi/sheragi outfits.txt
> +	"maneuver scan power" 25
```suggestion
```

2024-07-20 04:23 UTC, TheGiraffe3 commented on data/sheragi/sheragi outfits.txt
> +	"fuel scan power" 30
For the energy though, it does say it's an electronic system...

2024-07-20 04:24 UTC, TheGiraffe3 commented
I just liked the idea of the EWS being able to do everything, but I suppose then you have balance issues.

2024-07-20 09:52 UTC, Zitchas commented
So do I. Especially since we don't get a complete ecosystem for the Sheragi. It also makes sense that they'd have some form of info for most of these things, just not at the same level.c

Likewise, the Sheragi are theoretically supposed to be a bit lower tech, overall, than humanity. Not universally so, but overall. Sensors are a bit of a strong point in the way they were initially established, though, so that's reasonable to keep.

And as a side thing, I find that *all* the sensor suites are on the short side and should be a bit farther. 

Hmm... Idea: 
- Bump the current passive sensor values (let's say they are the "core" elements up by 5.
- Add the velocity option at the same range as the weapon scan (identifying how fast something is going is very basic analysis, after all)
- Add energy and fuel at a value of 20, so quite close range. 

This will give a bit of a cascading info effect, which I personally find interesting/neat and make it stand out as something unique.

2024-07-20 10:15 UTC, TheGiraffe3 commented
Passive sensor values I assume mean the ones currently in?

2024-07-20 12:12 UTC, Zitchas commented
Yes, like that.

I suppose I should clarify:

When I refer to "active scanners", I mean the scans that the player has to issue a command to use. Namely, the cargo and outfit scanning.

When I refer to "passive scanners", I mean the things that provide information passively with no more than having to have a target (and not even that, for asteroid scanners).

Anyway, those values look good. I'll merge it once the checks are done.

2024-07-20 12:13 UTC, Zitchas approved these changes

2024-07-20 12:17 UTC, merged

2024-07-20 12:17 UTC, Zitchas commented
Thanks for spotting and working on this!

2024-07-20 12:18 UTC, TheGiraffe3 commented
No problem!