Add a thermal scanner mission
endless-sky/Endless-Sky-Delta pull request #90
Opened 2024-10-01 17:37 UTC by TheGiraffe3

As requested in #15.

2024-10-02 03:40 UTC, TheGiraffe3 commented on data/human/free worlds side plots.txt
> +			`	"We need you to fly to <waypoints> and disable the Doombat, which is still armed with flamethrowers. Another <npc model>, the <npc>, will fly by you with the new scanners installed and take read
```suggestion
			`	"We need you to fly to <waypoints> and disable the Doombat, which is still armed with flamethrowers. Another <npc model>, the <npc>, will fly by you with the new scanners installed and take readings on the battle. Then come back here and report.`
```

2024-10-06 02:07 UTC, Zitchas commented
First and second glance look good. Once I get the chance to play through it, I'll merge this. Should be <24h.

2024-10-06 12:10 UTC, Zitchas requested changes
One change that needs to be done so that the mission text lists the waypoint properly and the player knows where to go, other than that it looks good.

I feel like there's something I'm missing, some detail in the back of my head, but I can't put my finger on it. With the addition of the waypoint line the missions all work properly.

2024-10-06 12:10 UTC, Zitchas commented on data/human/free worlds side plots.txt
> +	to offer
```suggestion
	source "Rust"
	waypoint "Ildaria"
	to offer
```

Without this, the mission description text just says "A test ship with flamethrowers is in the <waypoints> system." without specifying where that is. Nor does it provide any kind of indicator without having this specified.

2024-10-06 13:49 UTC, Zitchas approved these changes
Looks good now. Thanks!

2024-10-06 13:51 UTC, merged

2024-10-06 14:02 UTC, TheGiraffe3 commented
You merged that. Might it be good to revert and squash?

2024-10-06 18:08 UTC, Zitchas commented
Thanks for spotting that. Repository has been hard reset to prior to doing so. Could you re-PR please?